version: 1.2.11.1.{build}

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true

image:
  - Visual Studio 2019

before_build:
  - cmd: cmake .

build:
  project: "zlib.sln"

platform:
  - x64
configuration:
  - Debug
  - Release

test_script:
  - ps: "%APPVEYOR_BUILD_FOLDER%/%CONFIGURATION%/example.exe --junit %APPVEYOR_BUILD_FOLDER%/%CONFIGURATION%/junit-results.xml" -ErrorVariable testError
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path "$($env:APPVEYOR_BUILD_FOLDER)\$($env:CONFIGURATION)\junit-results.xml"))
  - ps: if($testError) { throw $testError }