version: 1.2.11.{build}

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

shallow_clone: true

image:
  - Visual Studio 2019

build:
  project: "Projects/VisualStudio/max.sln"
  parallel: true

platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release

test_script:
  - "%APPVEYOR_BUILD_FOLDER%/Projects/VisualStudio/maxAutomatedTests/%PLATFORM%/%CONFIGURATION%/maxAutomatedTests.exe"
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Tooling\AppVeyor\junit-results.xml))
